import type { Config } from 'tailwindcss';

const config: Config = {
  content: ['./app/**/*.{js,ts,jsx,tsx,mdx}'],
  theme: {
    screens: {
      xs:     '430px',
      mobile: '560px',
      sm:     '600px',
      md:     '940px',
      lg:     '1180px',
      xl:     '1280px',
    },
    extend: {
      colors: {
        accent:            'var(--accent)',
        'accent-2':        'var(--accent-2)',
        'accent-contrast': 'var(--accent-contrast)',
        'accent-soft':     'var(--accent-soft)',
        'accent-ink':      'var(--accent-ink)',
        surface:           'var(--surface)',
        'surface-2':       'var(--surface-2)',
        bg:                'var(--bg)',
        muted:             'var(--muted)',
        line:              'var(--line)',
        'site-text':       'var(--text)',
        'on-surface-variant':        '#3c4949',
        'surface-container-highest': '#dbe4ed',
        'primary-fixed-dim':         '#52d9de',
        'primary-fixed':             '#73f6fb',
        'inverse-primary':           '#52d9de',
        'error-container':           '#ffdad6',
        'on-primary-fixed':          '#002021',
        'on-primary-fixed-variant':  '#004f52',
        'on-primary-container':      '#006265',
        'on-primary':                '#ffffff',
        'on-secondary':              '#ffffff',
        'on-secondary-container':    '#656464',
        'on-secondary-fixed':        '#1c1b1b',
        'on-secondary-fixed-variant':'#474646',
        'on-tertiary':               '#ffffff',
        'on-tertiary-fixed':         '#191c1d',
        'on-tertiary-fixed-variant': '#454748',
        'on-tertiary-container':     '#555859',
        'on-error':                  '#ffffff',
        'on-error-container':        '#93000a',
        'on-surface':                '#141d23',
        'on-background':             '#141d23',
        'inverse-on-surface':        '#e9f2fb',
        'inverse-surface':           '#293138',
        'outline':                   '#6c7a7a',
        'outline-variant':           '#bbc9c9',
        'surface-tint':              '#00696c',
        'surface-dim':               '#d2dbe4',
        'surface-bright':            '#f6faff',
        'surface-container':         '#e6eff8',
        'surface-container-high':    '#e0e9f2',
        'surface-container-low':     '#ecf5fe',
        'surface-container-lowest':  '#ffffff',
        'surface-variant':           '#dbe4ed',
        'tertiary-fixed-dim':        '#c5c7c8',
        'tertiary-fixed':            '#e1e3e4',
        'tertiary-container':        '#cdcecf',
        'secondary-fixed':           '#e5e2e1',
        'secondary-fixed-dim':       '#c8c6c5',
        'secondary-container':       '#e5e2e1',
        'primary-container':         '#5ce1e6',
        'background':                '#f6faff',
        'primary':                   '#00696c',
        'tertiary':                  '#5c5f60',
        'secondary':                 '#5f5e5e',
        'error':                     '#ba1a1a',
      },
      fontFamily: {
        display:       ['var(--font-hanken-grotesk)', 'Hanken Grotesk', 'sans-serif'],
        body:          ['var(--font-inter)', 'Inter', 'sans-serif'],
        mono:          ['var(--font-jetbrains-mono)', 'JetBrains Mono', 'monospace'],
        'label-md':    ['"JetBrains Mono"'],
        'body-lg':     ['"Inter"'],
        'display-lg':  ['"Hanken Grotesk"'],
        'headline-md': ['"Hanken Grotesk"'],
        'headline-lg': ['"Hanken Grotesk"'],
        'label-sm':    ['"JetBrains Mono"'],
        'body-md':     ['"Inter"'],
      },
      fontSize: {
        'label-md':    ['14px', { lineHeight: '20px', letterSpacing: '0.05em', fontWeight: '500' }],
        'body-lg':     ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'display-lg':  ['56px', { lineHeight: '64px', letterSpacing: '-0.02em', fontWeight: '800' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'label-sm':    ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '500' }],
        'body-md':     ['16px', { lineHeight: '24px', fontWeight: '400' }],
      },
      borderRadius: {
        site:     '14px',
        'site-lg':'22px',
        DEFAULT:  '0.25rem',
        lg:       '0.5rem',
        xl:       '0.75rem',
      },
      maxWidth: {
        wrap:            '1180px',
        'nav-inner':     '1280px',
        'container-max': '1280px',
      },
      boxShadow: {
        'btn-primary':       '0 12px 0 -2px var(--accent-ink)',
        'btn-primary-hover': '0 8px 0 -2px var(--accent-ink)',
        'card-hover':        '0 30px 60px -34px rgba(0,0,0,.4)',
        'tcard-hover':       '0 28px 54px -34px rgba(0,0,0,.4)',
        'elevation-1':       '0px 20px 40px rgba(92,225,230,0.06)',
        'nav-scrolled':      '0 2px 20px -8px rgba(0,0,0,.1)',
      },
      keyframes: {
        modalFadeIn: {
          from: { opacity: '0', transform: 'translateY(10px)' },
          to:   { opacity: '1', transform: 'none' },
        },
        mobileNavIn: {
          from: { opacity: '0', transform: 'translateY(-10px)' },
          to:   { opacity: '1', transform: 'none' },
        },
      },
      animation: {
        'modal-in':      'modalFadeIn .22s ease',
        'modal-in-slow': 'modalFadeIn .28s ease',
        'nav-in':        'mobileNavIn .22s ease',
      },
      spacing: {
        md:               '24px',
        xl:               '80px',
        lg:               '48px',
        'margin-desktop': '64px',
        xs:               '4px',
        gutter:           '24px',
        base:             '8px',
        'margin-mobile':  '16px',
        sm:               '12px',
        'section-gap':    '120px',
        'stack-lg':       '32px',
        'stack-md':       '16px',
        'stack-sm':       '8px',
      },
    },
  },
  plugins: [
    require('@tailwindcss/typography'),
  ],
};

export default config;
