import type { Config } from 'tailwindcss';

const config: Config = {
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'on-surface-variant': '#3c4949',
        'surface-container-highest': '#dbe4ed',
        'primary-fixed-dim': '#52d9de',
        'tertiary-fixed-dim': '#c5c7c8',
        'surface-dim': '#d2dbe4',
        'on-secondary-container': '#656464',
        'secondary-fixed': '#e5e2e1',
        'on-primary-fixed': '#002021',
        'on-secondary': '#ffffff',
        'inverse-on-surface': '#e9f2fb',
        'outline': '#6c7a7a',
        'on-tertiary-fixed-variant': '#454748',
        'primary-fixed': '#73f6fb',
        'inverse-primary': '#52d9de',
        'error-container': '#ffdad6',
        'on-primary-fixed-variant': '#004f52',
        'on-primary-container': '#006265',
        'tertiary-fixed': '#e1e3e4',
        'background': '#f6faff',
        'on-tertiary': '#ffffff',
        'on-secondary-fixed-variant': '#474646',
        'inverse-surface': '#293138',
        'surface-tint': '#00696c',
        'on-error': '#ffffff',
        'tertiary-container': '#cdcecf',
        'error': '#ba1a1a',
        'surface-container': '#e6eff8',
        'on-error-container': '#93000a',
        'secondary-fixed-dim': '#c8c6c5',
        'on-tertiary-fixed': '#191c1d',
        'outline-variant': '#bbc9c9',
        'surface-container-high': '#e0e9f2',
        'surface': '#f6faff',
        'on-background': '#141d23',
        'surface-variant': '#dbe4ed',
        'primary': '#00696c',
        'surface-bright': '#f6faff',
        'on-tertiary-container': '#555859',
        'tertiary': '#5c5f60',
        'primary-container': '#5ce1e6',
        'surface-container-low': '#ecf5fe',
        'on-primary': '#ffffff',
        'secondary-container': '#e5e2e1',
        'surface-container-lowest': '#ffffff',
        'secondary': '#5f5e5e',
        'on-secondary-fixed': '#1c1b1b',
        'on-surface': '#141d23',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
      },
      spacing: {
        'md': '24px',
        'xl': '80px',
        'lg': '48px',
        'margin-desktop': '64px',
        'xs': '4px',
        'gutter': '24px',
        'base': '8px',
        'margin-mobile': '16px',
        'sm': '12px',
        'section-gap': '120px',
        'stack-lg': '32px',
        'stack-md': '16px',
        'stack-sm': '8px',
      },
      fontFamily: {
        'label-md': '"JetBrains Mono"',
        'body-lg': '"Inter"',
        'display-lg': '"Hanken Grotesk"',
        'headline-md': '"Hanken Grotesk"',
        'headline-lg': '"Hanken Grotesk"',
        'label-sm': '"JetBrains Mono"',
        'body-md': '"Inter"',
      },
      fontSize: {
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.05em', fontWeight: '500' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'display-lg': ['56px', { lineHeight: '64px', letterSpacing: '-0.02em', fontWeight: '800' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '500' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
      },
      maxWidth: {
        'container-max': '1280px',
      },
      boxShadow: {
        'elevation-1': '0px 20px 40px rgba(92,225,230,0.06)',
      },
    },
  },
  plugins: [],
};

export default config;
